name: CI for Cypress Tests

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t cypress-tests .

      - name: Run Cypress tests
        run: docker run cypress-tests

      - name: Archive Cypress results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-failure-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports
